export const SETTINGS_TABS = [
  { id: "account", label: "Account", heading: "Account" },
  { id: "security", label: "Security", heading: "Security" },
  { id: "privacy", label: "Privacy", heading: "Privacy" },
  { id: "verification", label: "Verification", heading: "Verification" },
  { id: "notifications", label: "Notifications", heading: "Notifications" },
  { id: "communication-preferences", label: "Communication Preferences", heading: "Communication Preferences" },
  { id: "appearance", label: "Appearance", heading: "Appearance" },
  { id: "accessibility", label: "Accessibility", heading: "Accessibility" },
  { id: "sessions", label: "Sessions", heading: "Sessions" },
  { id: "devices", label: "Devices", heading: "Devices" },
  { id: "linked-accounts", label: "Linked Accounts", heading: "Linked Accounts" },
  { id: "connected-apps", label: "Connected Apps", heading: "Connected Apps" },
  { id: "integrations", label: "Integrations", heading: "Integrations" },
  { id: "api-webhooks", label: "API & Webhooks", heading: "API & Webhooks" },
  { id: "billing", label: "Billing", heading: "Billing" },
  { id: "plans-upgrades", label: "Plans & Upgrades", heading: "Plans & Upgrades" },
  { id: "usage-limits", label: "Usage & Limits", heading: "Usage & Limits" },
  { id: "storage", label: "Storage", heading: "Storage" },
  { id: "backups", label: "Backups", heading: "Backups" },
  { id: "activity", label: "Activity", heading: "Activity" },
  { id: "audit-logs", label: "Audit Logs", heading: "Audit Logs" },
  { id: "security-logs", label: "Security Logs", heading: "Security Logs" },
  { id: "region", label: "Region", heading: "Region" },
  { id: "workspace-branding", label: "Workspace Branding", heading: "Workspace Branding" },
  { id: "ai-preferences", label: "AI Preferences", heading: "AI Preferences" },
  { id: "roles-permissions", label: "Roles & Permissions", heading: "Roles & Permissions" },
  { id: "team-management", label: "Team Management", heading: "Team Management" },
  { id: "admin-controls", label: "Admin Controls", heading: "Admin Controls" },
  { id: "compliance", label: "Compliance", heading: "Compliance" },
  { id: "consent", label: "Consent", heading: "Consent" },
  { id: "legal", label: "Legal", heading: "Legal" },
  { id: "support", label: "Support", heading: "Support" },
  { id: "support-tickets", label: "Support Tickets", heading: "Support Tickets" },
  { id: "release-notes", label: "Release Notes", heading: "Release Notes" },
  { id: "system-status", label: "System Status", heading: "System Status" },
  { id: "experiments", label: "Experiments", heading: "Experiments" },
  { id: "labs-beta-features", label: "Labs / Beta Features", heading: "Labs / Beta Features" },
  { id: "data-export", label: "Data Export", heading: "Data Export" },
  { id: "danger-zone", label: "Danger Zone", heading: "Danger Zone" },
];

export const CATEGORY_FEATURES = {
  account: [
    "Profile photo upload",
    "Cover/banner image",
    "Full name edit",
    "Date of birth edit",
    "Gender edit",
    "Alternate email edit",
    "Recovery email",
    "Public profile slug",
    "Bio/about section",
    "Occupation/company field",
  ],
  security: [
    "Password strength meter",
    "Password last changed date",
    "Security question change",
    "Security answer change",
    "Authenticator app setup",
    "Backup codes",
    "Trusted devices",
    "Suspicious login detection",
    "Failed login attempts view",
    "IP/location login alerts",
  ],
  privacy: [
    "Profile visibility",
    "Email visibility",
    "Mobile visibility",
    "Search visibility",
    "Data sharing controls",
    "Analytics consent toggle",
    "Marketing consent toggle",
    "Personalized recommendations toggle",
    "AI data usage consent",
    "Cookie category controls",
  ],
  verification: [
    "Verification center summary",
    "Email verification badge/history",
    "Mobile verification badge/history",
    "Recovery email verification",
    "Re-verify mobile flow",
    "Pending verification state",
    "Verification expiry countdown",
    "Last verification date",
  ],
  notifications: [
    "Security alerts",
    "Billing alerts",
    "Subscription renewal reminders",
    "Mentions alerts",
    "Comments/replies alerts",
    "Product update alerts",
    "Release update alerts",
    "Daily digest",
    "Weekly digest",
    "Notification frequency selector",
  ],
  "communication-preferences": [
    "Preferred contact channel",
    "Promotional emails toggle",
    "Support contact preference",
    "Newsletter toggle",
    "Renewal reminder channel choice",
    "Critical alerts override",
    "Language for communications",
    "Quiet hours",
    "Do-not-disturb schedule",
    "Contact time preference",
  ],
  appearance: [
    "Dark mode",
    "System theme sync",
    "Accent color picker",
    "Layout density",
    "Sidebar style preference",
    "Card/list view default",
    "Dashboard layout presets",
    "Background style",
    "Custom wallpaper",
    "Reduced motion theme mode",
  ],
  accessibility: [
    "High contrast mode",
    "Text scaling",
    "Dyslexia-friendly font",
    "Keyboard navigation mode",
    "Focus highlight strength",
    "Screen-reader optimization",
    "Reduced motion",
    "Colorblind-safe palette",
    "Larger click targets",
    "Caption/subtitle preference",
  ],
  sessions: [
    "Active sessions list",
    "Session start time",
    "Browser/device per session",
    "IP/location per session",
    "Sign out single session",
    "Sign out all sessions",
    "Session expiry control",
    "Recent session history",
    "Suspicious session flag",
    "Current session badge",
  ],
  devices: [
    "Known devices list",
    "Device nicknames",
    "Last active time",
    "OS/browser details",
    "Remove trusted device",
    "Device risk status",
    "New device alert toggle",
    "Remember device toggle",
    "Mobile/desktop grouping",
    "Device verification history",
  ],
  "linked-accounts": [
    "GitHub link",
    "Microsoft link",
    "Apple link",
    "Slack link",
    "Discord link",
    "Primary sign-in provider selector",
    "Linked account permissions view",
    "Reconnect expired account",
    "Linked account history",
    "Account sync status",
  ],
  "connected-apps": [
    "Third-party app list",
    "App permission scopes",
    "Revoke app access",
    "Last app activity",
    "Connected app approval status",
    "Installed app history",
    "App risk level",
    "Trusted app toggle",
    "App login source",
    "Temporary access tokens",
  ],
  integrations: [
    "Slack integration",
    "Google Drive integration",
    "GitHub integration",
    "Notion integration",
    "Dropbox integration",
    "Zapier/Make integration",
    "CRM integrations",
    "Integration health status",
    "Sync frequency",
    "Integration logs",
  ],
  "api-webhooks": [
    "Personal API keys",
    "Workspace API keys",
    "Regenerate key",
    "Revoke key",
    "Webhook creation",
    "Webhook secret rotation",
    "Webhook event selection",
    "Delivery logs",
    "Retry failed webhook",
    "Test webhook action",
  ],
  billing: [
    "Billing address",
    "Company name",
    "Tax/GST number",
    "Auto-renew toggle",
    "Saved card view",
    "Replace payment method",
    "Refund status",
    "Billing contact",
    "Upcoming renewal preview",
    "Billing history filters",
  ],
  "plans-upgrades": [
    "Upgrade plan action",
    "Downgrade plan action",
    "Plan comparison table",
    "Feature unlock preview",
    "Team plan option",
    "Annual/monthly switch",
    "Promo code field",
    "Free trial status",
    "Renewal options",
    "Add-on purchase options",
  ],
  "usage-limits": [
    "Document query usage",
    "Image generation usage",
    "Object detection usage",
    "Storage used",
    "API request count",
    "Monthly limit bar",
    "Daily usage graph",
    "Overage warnings",
    "Feature quota breakdown",
    "Usage reset date",
  ],
  storage: [
    "Total used storage",
    "File type breakdown",
    "Largest files list",
    "Storage cleanup suggestions",
    "Deleted file retention window",
    "Upload limit display",
    "Per-feature storage usage",
    "Archived files area",
    "Duplicate file detection",
    "Storage warning threshold",
  ],
  backups: [
    "Manual backup trigger",
    "Scheduled backups",
    "Backup history",
    "Last backup date",
    "Backup size",
    "Restore point list",
    "Download backup",
    "Auto-backup toggle",
    "Backup verification status",
    "Backup retention period",
  ],
  activity: [
    "Settings change history",
    "Billing activity",
    "Linked account activity",
    "Export activity",
    "Security activity",
    "Login activity",
    "Workspace actions",
    "Search/filter activity",
    "Category-based activity",
    "Activity export",
  ],
  "audit-logs": [
    "Admin action log viewer",
    "User role changes",
    "Billing admin actions",
    "Export logs",
    "Login policy changes",
    "Data deletion logs",
    "Integration config changes",
    "Search/filter logs",
    "Severity tags",
    "Audit export",
  ],
  "security-logs": [
    "Failed login logs",
    "Account lock events",
    "Password change logs",
    "2FA changes",
    "Device approval logs",
    "Suspicious login logs",
    "API key usage logs",
    "Webhook security failures",
    "Role escalation logs",
    "Security event export",
  ],
  region: [
    "App locale",
    "Currency preference",
    "Number format",
    "Language per workspace",
    "Regional compliance note",
    "Data residency preference",
    "Regional feature availability",
    "Tax region",
    "Working week preference",
    "First day of week",
  ],
  "workspace-branding": [
    "Workspace logo",
    "Workspace banner",
    "Workspace name edit",
    "Brand color",
    "Accent theme",
    "Custom favicon",
    "Email branding",
    "Invoice branding",
    "Welcome screen branding",
    "Footer/company text",
  ],
  "ai-preferences": [
    "Default AI model",
    "Response tone",
    "Response length default",
    "Creativity level",
    "Safety strictness",
    "Auto-suggestions toggle",
    "AI memory preference",
    "Personalization level",
    "Default assistant mode",
    "Experimental AI features",
  ],
  "roles-permissions": [
    "Role matrix view",
    "Custom roles",
    "Permission toggles",
    "Read/write/admin split",
    "Feature-level access",
    "Billing access control",
    "Export permission control",
    "Audit access control",
    "Temporary role assignment",
    "Role history",
  ],
  "team-management": [
    "Invite team members",
    "Pending invites",
    "Member directory",
    "Department/team tags",
    "Manager assignment",
    "Team activity view",
    "Seat usage",
    "Remove member action",
    "Bulk role update",
    "Team access summary",
  ],
  "admin-controls": [
    "Admin action oversight",
    "User escalation controls",
    "Administrative review queue",
    "Privileged access approval",
    "Override safeguards",
    "Moderator health checks",
    "Incident assignment",
    "Admin console shortcuts",
    "Emergency lock tools",
    "Control audit markers",
  ],
  compliance: [
    "GDPR tools",
    "Data residency settings",
    "Retention policy",
    "Consent records",
    "Export compliance logs",
    "Deletion request tracking",
    "Policy acknowledgment history",
    "Compliance checklist",
    "Region-based compliance flags",
    "DPA reference section",
  ],
  consent: [
    "Marketing consent",
    "Analytics consent",
    "Cookie consent",
    "AI training consent",
    "Third-party sharing consent",
    "Consent history",
    "Consent last updated date",
    "Granular opt-ins",
    "Withdrawal controls",
    "Versioned consent tracking",
  ],
  legal: [
    "Full terms page",
    "Privacy policy page",
    "Cookie policy page",
    "Data processing terms",
    "Legal document version",
    "Last accepted date",
    "Download legal docs",
    "Region-specific legal notes",
    "Third-party licenses",
    "Legal contact info",
  ],
  support: [
    "Priority support routing",
    "Help center widgets",
    "Escalation contact info",
    "Support availability window",
    "Issue category quick links",
    "Diagnostic bundle sharing",
    "Self-service recovery tools",
    "Support callback scheduling",
    "Premium support indicator",
    "Support contact summary",
  ],
  "support-tickets": [
    "Ticket creation",
    "Ticket list/history",
    "Ticket status",
    "Priority level",
    "Category selection",
    "Attachment upload",
    "Reopen closed ticket",
    "Reply thread",
    "SLA/response timer",
    "Ticket filters/search",
  ],
  "release-notes": [
    "Product changelog",
    "Feature launch notes",
    "Bug fix notes",
    "Version history",
    "What’s new highlights",
    "Dismiss/read state",
    "Release category filters",
    "Coming soon panel",
    "Breaking changes notice",
    "Subscription-related updates",
  ],
  "system-status": [
    "API status",
    "Auth service status",
    "Payment service status",
    "Database status",
    "AI service status",
    "Uptime metrics",
    "Incident history",
    "Maintenance banner",
    "Degraded service notice",
    "Status refresh time",
  ],
  experiments: [
    "Experimental UI toggles",
    "Preview tools",
    "Test workflows",
    "Hidden feature access",
    "UI concept switcher",
    "Early rollout participation",
    "Internal-only flags",
    "Experiment feedback",
    "Reset experiments",
    "Experiment history",
  ],
  "labs-beta-features": [
    "Beta AI tools",
    "Beta integrations",
    "Beta model access",
    "Beta export tools",
    "Beta dashboards",
    "Join/leave beta",
    "Feedback form",
    "Beta disclaimer",
    "Feature stability labels",
    "Usage telemetry opt-in",
  ],
  "data-export": [
    "JSON export",
    "CSV export",
    "Activity export",
    "Billing export",
    "Linked account export",
    "Security log export",
    "Team/user export",
    "Scheduled exports",
    "Export history",
    "Export format selector",
  ],
  "danger-zone": [
    "Sign out all sessions",
    "Revoke all API keys",
    "Remove all connected apps",
    "Unlink all linked accounts",
    "Clear stored personal settings",
    "Archive account",
    "Deactivate workspace",
    "Transfer ownership",
    "Permanent workspace delete",
    "Hard-delete data request",
  ],
};
